### ISSUE TITLE
bad gateway Login to your account

### ISSUE THREAD

**Issue by salgari** [jc21/nginx-proxy-manager#1098]
hola, he instalado mariadb configurado en configuration.yaml (recorder:
  db_url: mysql://homeassistant:password@core-mariadb/homeassistant?charset=utf8mb4, he abierto los puertor 80 y 443, he instalado ngnix, pero cuando intento ingresar me da error error bad gateway, ¿alguna solución?, gracias
![Captura](https://user-images.githubusercontent.com/17797695/118348699-64e80000-b54c-11eb-99d3-dc83601494c9.JPG)

**Comment by salgari** [comment]
o se esto ayuda

2021/05/15 07:25:23 [error] 574#574: *3588 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.226, server: nginxproxymanager, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "192.168.1.226:81", referrer: "http://192.168.1.226:81/"

**Comment by netstx** [comment]
I have the same issue after upgrading to 2.9.3, looked at the logs, but haven't figured it out yet

**Comment by salgari** [comment]
. I have enabled on the router nat loopback. Thanks

**Comment by jc21** [comment]
`docker logs name_of_npm_container`
and look for obvious problems.

**Comment by netstx** [comment]
@jc21 i'm running npm on a alpine linux LXC container (inside proxmox), I was digging on /var/log, but didn't find anything. have you seen this error before?

**Comment by salgari** [comment]
I'm sorry, I don't know what it can be

**Comment by Callum-W** [comment]
I'm having the same issue.  It seems to be a problem connecting to the database

`error     getaddrinfo ENOTFOUND db`

**Comment by sadu-io** [comment]
@Callum-W  Exact same issue here. Any luck on your end?  

When I visit jc21/nginx-proxy-manager:latest in the browser on port 81, I see "Bad Gateway" when attempting to login via admin. My log returns the same error you mentioned. 

```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DISABLE_IPV6: 'true'
      # These are the settings to access your db
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./Users/brittanysalas/.config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: 'webhippie/mariadb:latest'
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 'npm'
      MARIADB_DATABASE: 'npm'
      MARIADB_USERNAME: 'npm'
      MARIADB_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
```



I am on a MacOS with the latest update. I am a noob and cannot describe my environment in further detail.
