### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by razzam21** [jc21/nginx-proxy-manager#11]
NOTE:  This is a first time trying to log in after deploying the container.

"Internal error" appears on the screen after entering the provided username and password.

This line appears in the logs.
[9/3/2018] [12:18:47 PM] [Express ] › ⚠  warning                      Configuration property "jwt.pub" is not defined

**Comment by jc21** [comment]
A few questions...
1. Do you definitely have a config json file mounted as `/app/config/production.json` ?
2. Are you importing from a version 1 configuration?

**Comment by jc21** [comment]
That is very strange. I've just tested a clean install with the latest image and things are working fine. The fact that it wrote the keys to the file means it should be able to read from them. If you're using docker-compose, can you attach the output of this command: `docker-compose config`

Here's mine:

```yml
services:
  app:
    depends_on:
    - db
    environment:
      FORCE_COLOR: '1'
    image: jc21/nginx-proxy-manager:2
    ports:
    - 80:80/tcp
    - 81:81/tcp
    - 443:443/tcp
    restart: always
    volumes:
    - /opt/nginx-proxy-manager/config.json:/app/config/production.json:rw
    - /opt/nginx-proxy-manager/data:/data:rw
    - /opt/nginx-proxy-manager/letsencrypt:/etc/letsencrypt:rw
  db:
    environment:
      MYSQL_DATABASE: npm
      MYSQL_PASSWORD: npm
      MYSQL_ROOT_PASSWORD: npm
      MYSQL_USER: npm
    image: mariadb:10.3.7
    restart: always
    volumes:
    - /opt/nginx-proxy-manager/data/mysql:/var/lib/mysql:rw
version: '2.0'
```

Perhaps
