### ISSUE TITLE
 ER_ACCESS_DENIED_ERROR: Access denied

### ISSUE THREAD

**Issue by tiritibambix** [jc21/nginx-proxy-manager#1161]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes, but no solution worked

**Describe the bug**
I get an error while deploying the custom template

**Nginx Proxy Manager Version**
Latest

**To Reproduce**
1. Go to portainer

2. Create custom template

3. here's my template (version 3 didn't want to install, so I used v2)
```
version: '2'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "steph"
      DB_MYSQL_PASSWORD: "MYPASSWD"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'MYPASSWD'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'steph'
      MYSQL_PASSWORD: 'MYPASSWD'
    volumes:
      - ./data/mysql:/var/lib/mysql
```

4. Error :
_s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[6/7/2021] [5:51:21 PM] [Global   ] › ✖  error     ER_ACCESS_DENIED_ERROR: Access denied for user 'steph'@'172.18.0.3' (using password: YES),
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01_s6-secret-init.sh: executing... ,
[cont-init.d] 01_s6-secret-init.sh: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
❯ Enabling IPV6 in hosts: /etc/nginx/conf.d,
  ❯ /etc/nginx/conf.d/production.conf,
  ❯ /etc/nginx/conf.d/default.conf,
  ❯ /etc/nginx/conf.d/include/proxy.conf,
  ❯ /etc/nginx/conf.d/include/force-ssl.conf,
  ❯ /etc/nginx/conf.d/include/assets.conf,
  ❯ /etc/nginx/conf.d/include/ip_ranges.conf,
  ❯ /etc/nginx/conf.d/include/ssl-ciphers.conf,
  ❯ /etc/nginx/conf.d/include/block-exploits.conf,
  ❯ /etc/nginx/conf.d/include/letsencrypt-acme-challenge.conf,
  ❯ /etc/nginx/conf.d/include/resolvers.conf,
❯ Enabling IPV6 in hosts: /data/nginx,
[6/7/2021] [5:51:29 PM] [Global   ] › ✖  error     ER_ACCESS_DENIED_ERROR: Access denied for user 'steph'@'172.18.0.3' (using password: YES),_

**Operating System**
RaspberryPi OS up to date
Raspberry Pi 4B 4Go

**Additional context**
I'm a total noob, so please, bare with me.

I can access the web panel at MYPIADRESS:81 but the default _Email: admin@example.com Password: changeme_ don't log me in.

**Comment by chaptergy** [comment]
Sounds like the database did not set up correctly, have you looked into the logs of the database image?

**Comment by frisodubach** [comment]
The problem is with Raspberry Pi and maria-db. For some reason, this db isn't compatible with the Pi, and even the arm versions don't work, so adding a tag is not going to help. You can do one of two things as far as I know. 

1. Switch to the yobasystems/alpine-mariadb database image. (The docker compose for this on the website is incorrect. Instead you can find it here: https://github.com/jc21/nginx-proxy-manager/tree/develop/docs/setup).
2. Use SQLite as a database. 

Docker compose examples for both:

1. yobasystems
```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "user"
      DB_MYSQL_PASSWORD: "password"
      DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data/nginx-proxy-manager:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: yobasystems/alpine-mariadb:latest
    restart: unless-stopped
environment:
      PUID: 1000
      PGID: 1000
      TZ: "Europe/Amsterdam"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - ./data/mariadb:/config
```

2. SQLite
```
version: "2"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

```
