### ISSUE TITLE
Pihole with nginx-proxy-manager

### ISSUE THREAD

**Issue by samad20** [jc21/nginx-proxy-manager#1206]
Since port 80 and 443 is reserved for Nginx, how can i install pi hole on docker?

**Comment by bpycinski** [comment]
There is no problem at all. Just map the port to anything other, e.g. 8080 See my docker-compose, it works very well:

    services:
      pihole:
        container_name: pihole
        image: pihole/pihole:latest
        ports:
        - "8080:80/tcp"
        - "53:53/tcp"
        - "53:53/udp"
        - "67:67/udp"
        environment:
        - WEBPASSWORD=asecret
        - INTERFACE=eth0
        - USER_UID=1000
        - USER_GID=1000
        volumes:
        - ./volumes/pihole/etc-pihole/:/etc/pihole/
        - ./volumes/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
        restart: unless-stopped
        networks:
        - internal_nw

But you can even get rid of publishing port 80. Just use npm to forward `pihole.mydomain.com` to `pihole:80`.

**Comment by scottpageindysoft** [comment]
I run the same on my network, and the solution above is correct.
Have your router point 80 and 443 to NPM, then have NPM reverse proxy to all other sites, including PiHole web interface, internally

I've had zero issues with this, and I run 80 sites exposed through NPM.

All other internal sites can use any other port that doesn't conflict with others.

**Comment by asyba** [comment]
> I run the same on my network, and the solution above is correct.
> Have your router point 80 and 443 to NPM, then have NPM reverse proxy to all other sites, including PiHole web interface, internally
> 
> I've had zero issues with this, and I run 80 sites exposed through NPM.
> 
> All other internal sites can use any other port that doesn't conflict with others.

what about using only for lan local? for example if I want to access some service with a NPM domain name example.service to 192.168.1.100:8989 ?
I have pihole and NPM docker compose, but going to example.service is not happening nothing.

**Comment by BenJule** [comment]
i get an ERR_CONNECTION_TIMED_OUT!

**Nginx-Proxy-Manager**

```
version: '3'
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/benlue/Docker/Nginx-Proxy-Manager/data:/data
      - /home/benlue/Docker/Nginx-Proxy-Manager/letsencrypt:/etc/letsencrypt
```

**Pi-Hole:**

```
version: "3"
 
services:
  pihole:
    container_name: pihole
    hostname: pi-hole
    image: pihole/pihole:latest
    ports:
      - "82:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'Colgate64@BenLue' # mot de passe de l'interface web
      INTERFACE: 'enp0s3'
    volumes:
      - '/var/run/docker.sock:/docker.sock'
      - '/home/benlue/Docker/Pihole/etc:/etc/pihole/'
      - '/home/benlue/Docker/Pihole/dnsmasq:/etc/dnsmasq.d/'
      - '/home/benlue/Docker/etc/resolv.conf:/etc/resolv.conf'
 
    restart: unless-stopped
```

**Comment by BenJule** [comment]
i get an ERR_CONNECTION_TIMED_OUT!

**Nginx-Proxy-Manager**

```
version: '3'
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/benlue/Docker/Nginx-Proxy-Manager/data:/data
      - /home/benlue/Docker/Nginx-Proxy-Manager/letsencrypt:/etc/letsencrypt
```

**Pi-Hole:**

```
version: "3"
 
services:
  pihole:
    container_name: pihole
    hostname: pi-hole
    image: pihole/pihole:latest
    ports:
      - "82:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'AweSomePass' # mot de passe de l'interface web
      INTERFACE: 'enp0s3'
    volumes:
      - '/var/run/docker.sock:/docker.sock'
      - '/home/benlue/Docker/Pihole/etc:/etc/pihole/'
      - '/home/benlue/Docker/Pihole/dnsmasq:/etc/dnsmasq.d/'
      - '/home/benlue/Docker/etc/resolv.conf:/etc/resolv.conf'
 
    restart: unless-stopped
```
