### ISSUE TITLE
Upgraded to latest version - no longer usable

### ISSUE THREAD

**Issue by danner26** [jc21/nginx-proxy-manager#1219]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
I am running NPM using docker-compse. where I ran `docker-compose pull` and then `docker-compose up -d`
When the app started, I logged into the new version and instead of having the dashboard/proxy hosts I cannot see anything. I check the Chrome console tab and see a bunch of these:
```
Welcome to Nginx Proxy Manager
main.bundle.js?v=2.9.4:3 You are logged in as REDACTED
main.bundle.js?v=2.9.4:1 TypeError: Cannot read property 'extend' of undefined
    at Object.213 (7.bundle.7.js:1)
    at r (main.bundle.js?v=2.9.4:1)
    at Object.181 (7.bundle.7.js:1)
    at r (main.bundle.js?v=2.9.4:1)
    at main.bundle.js?v=2.9.4:27
r.oe @ main.bundle.js?v=2.9.4:1
Promise.catch (async)
showNginxProxy @ main.bundle.js?v=2.9.4:27
Ze @ main.bundle.js?v=2.9.4:3
(anonymous) @ main.bundle.js?v=2.9.4:3
(anonymous) @ main.bundle.js?v=2.9.4:3
execute @ main.bundle.js?v=2.9.4:27
(anonymous) @ main.bundle.js?v=2.9.4:27
(anonymous) @ main.bundle.js?v=2.9.4:27
Ct @ main.bundle.js?v=2.9.4:3
loadUrl @ main.bundle.js?v=2.9.4:27
start @ main.bundle.js?v=2.9.4:27
(anonymous) @ main.bundle.js?v=2.9.4:3
m @ main.bundle.js?v=2.9.4:27
f @ main.bundle.js?v=2.9.4:27
d @ main.bundle.js?v=2.9.4:27
o.trigger @ main.bundle.js?v=2.9.4:27
O @ main.bundle.js?v=2.9.4:27
render @ main.bundle.js?v=2.9.4:27
ae @ main.bundle.js?v=2.9.4:27
show @ main.bundle.js?v=2.9.4:27
(anonymous) @ main.bundle.js?v=2.9.4:3
Promise.then (async)
onStart @ main.bundle.js?v=2.9.4:3
O @ main.bundle.js?v=2.9.4:27
start @ main.bundle.js?v=2.9.4:27
(anonymous) @ main.bundle.js?v=2.9.4:293
d @ main.bundle.js?v=2.9.4:27
l @ main.bundle.js?v=2.9.4:27
setTimeout (async)
(anonymous) @ main.bundle.js?v=2.9.4:27
u @ main.bundle.js?v=2.9.4:27
fireWith @ main.bundle.js?v=2.9.4:27
fire @ main.bundle.js?v=2.9.4:27
u @ main.bundle.js?v=2.9.4:27
fireWith @ main.bundle.js?v=2.9.4:27
ready @ main.bundle.js?v=2.9.4:27
V @ main.bundle.js?v=2.9.4:27
7.bundle.7.js:1 Uncaught (in promise) TypeError: Cannot read property 'extend' of undefined
    at Object.213 (7.bundle.7.js:1)
    at r (main.bundle.js?v=2.9.4:1)
    at Object.181 (7.bundle.7.js:1)
    at r (main.bundle.js?v=2.9.4:1)
    at main.bundle.js?v=2.9.4:27
```

**Nginx Proxy Manager Version**
2.9.4

**Screenshots**
![image](https://user-images.githubusercontent.com/8165027/124398704-1f8eb600-dce5-11eb-97db-4553898f33b3.png)

**Operating System**
Alpine Linux 3.13.5, Docker 20.10.3, Docker-Compose 1.27.4

**Additional context**
Logs: https://pastebin.com/swz7nvse

**Comment by danner26** [comment]
I also recreated the images to ensure it was built properly `docker-compose up --force-recreate --build -d`
That did not fix the issue

Here is my docker-compose.yml
```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: _**REDACTED**_
      DB_MYSQL_PASSWORD: _**REDACTED**_
      DB_MYSQL_NAME: "nginx_proxy_manager"
      DISABLE_IPV6: 'true'
      X_FRAME_OPTIONS: "sameorigin"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt/logs:/var/log/letsencrypt/
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: _**REDACTED**_
      MYSQL_DATABASE: _**REDACTED**_
      MYSQL_USER: _**REDACTED**_
      MYSQL_PASSWORD: _**REDACTED**_
      DISABLE_IPV6: 'true'
      X_FRAME_OPTIONS: "sameorigin"
    volumes:
      - ./data/mysql:/var/lib/mysql
networks:
  default:
    external:
      name: proxynet
```
