### ISSUE TITLE
works with arm

### ISSUE THREAD

**Issue by foxboi740** [jc21/nginx-proxy-manager#1260]
will this container work with an ARM base cpu? looked around on the site and say nothing about it?

**Comment by R2DToo** [comment]
Does this answer your question? 
https://nginxproxymanager.com/setup/#running-on-raspberry-pi-arm-devices

**Comment by frisodubach** [comment]
In my experience, running on ARM is super annoying and problematic. It's particularly a problem as MariaDB has issues with running on ARM based devices. However using an SQLite database fixed pretty much everything for me.

**Comment by johntdavis84** [comment]
It works great on ARM. I've been using it on a 4GB Raspberry Pi 4b for more than a year, without issues.

I'm not using it with MySQL, given the size of my deployment is small. It seems to do just fine using SQLite (see, here: [https://nginxproxymanager.com/setup/#running-on-raspberry-pi-arm-devices](https://nginxproxymanager.com/setup/#running-on-raspberry-pi-arm-devices) ). I've also got a MariaDB server running bare metal on my Pi...I might switch my installation over to that just to see what happens.

**Comment by hugalafutro** [comment]
This `docker-compose.yml` works without issue on rpi3, rpi4 and x64 vm or physical pc as I've used it on all of those for extended periods of time. I use ~20-ish proxy hosts.
```
version: '3'
services:
  app:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '8080:80'
      - '81:81'
      - '8443:443'
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    environment:
      TZ: Europe/London
      X_FRAME_OPTIONS: "sameorigin"
      DISABLE_IPV6: 'true'

  db:
    container_name: nginx-proxy-manager_db
    image: yobasystems/alpine-mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASS} --execute \"SELECT 1;\""
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
```
