### ISSUE TITLE
docker stack help

### ISSUE THREAD

**Issue by vidhya199** [jc21/nginx-proxy-manager#1299]
Working with docker stack i have docker stack as below its not working pales suggest me changes .. i dont want a bind because its generate unnamed volumes.

```yml
version: '3.4'

volumes:
   nfsdata:
      driver: local
      driver_opts:
        type: "nfs"
        o: "addr=192.168.0.140,rw,nfsvers=4,async"
        device: ":/mnt/data/volumes/nginx-proxy-manager/data"
        
   nfsletsencrypt:
      driver: local
      driver_opts:
        type: "nfs"
        o: "addr=192.168.0.140,rw,nfsvers=4,async"
        device: ":/mnt/data/volumes/nginx-proxy-manager/letsencrypt"
        
   nfsmysql:
      driver: local
      driver_opts:
        type: "nfs"
        o: "addr=192.168.0.140,rw,nfsvers=4,async"
        device: ":/mnt/data/volumes/nginx-proxy-manager/mysql"
     
networks:
  nginx_network:
    driver: overlay
    attachable: true

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - nfsdata:/data
      - nfsmysql:/data/mysql
      - nfsletsencrypt:/etc/letsencrypt
    networks:
      - nginx_network
  db:
    image: 'jc21/mariadb-aria:10.4'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - nfsmysql:/var/lib/mysql
    networks:
      - nginx_network
```
