### ISSUE TITLE
Error: Segmentation fault  (core dumped) node 

### ISSUE THREAD

**Issue by NavneetProject** [jc21/nginx-proxy-manager#1307]
Hello, Elders of nginx :-)

I am learning to create nginx-proxy-manager on my test instance docker swarm, I am using 1core ARM and 6gb ram, below is my stack:

```yml
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '8081:81'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - /data
      - /etc/letsencrypt
```

However, it's not working and giving me the below error, any suggestion on how can I fix

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01_perms.sh: executing... 
Changing ownership of /data/logs to 0:0
[cont-init.d] 01_perms.sh: exited 0.
[cont-init.d] 01_s6-secret-init.sh: executing... 
[cont-init.d] 01_s6-secret-init.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Generating dummy SSL certificate...
Generating a RSA private key
[services.d] done.
..+++++
......................+++++
writing new private key to '/data/nginx/dummykey.pem'
-----
Complete
[8/11/2021] [10:37:24 AM] [Global   ] › ℹ  info      Generating Sqlite db configuration from environment variables
[8/11/2021] [10:37:24 AM] [Global   ] › ℹ  info      Wrote db configuration to config file: ./config/production.json
❯ Enabling IPV6 in hosts: /etc/nginx/conf.d
  ❯ /etc/nginx/conf.d/default.conf
  ❯ /etc/nginx/conf.d/include/assets.conf
  ❯ /etc/nginx/conf.d/include/block-exploits.conf
  ❯ /etc/nginx/conf.d/include/force-ssl.conf
  ❯ /etc/nginx/conf.d/include/ip_ranges.conf
  ❯ /etc/nginx/conf.d/include/letsencrypt-acme-challenge.conf
  ❯ /etc/nginx/conf.d/include/proxy.conf
  ❯ /etc/nginx/conf.d/include/ssl-ciphers.conf
  ❯ /etc/nginx/conf.d/include/resolvers.conf
  ❯ /etc/nginx/conf.d/production.conf
❯ Enabling IPV6 in hosts: /data/nginx
./run: line 18:   237 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
./run: line 18:   289 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
./run: line 18:   302 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
[8/11/2021] [10:37:29 AM] [Migrate  ] › ℹ  info      Current database version: none
./run: line 18:   324 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
[8/11/2021] [10:37:31 AM] [Migrate  ] › ℹ  info      Current database version: none
./run: line 18:   337 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
[8/11/2021] [10:37:33 AM] [Migrate  ] › ℹ  info      Current database version: none
./run: line 18:   350 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
[8/11/2021] [10:37:34 AM] [Migrate  ] › ℹ  info      Current database version: none
./run: line 18:   372 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
[8/11/2021] [10:37:36 AM] [Migrate  ] › ℹ  info      Current database version: none
./run: line 18:   385 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
[8/11/2021] [10:37:38 AM] [Migrate  ] › ℹ  info      Current database version: none
./run: line 18:   398 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
[8/11/2021] [10:37:40 AM] [Migrate  ] › ℹ  info      Current database version: none
./run: line 18:   421 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
