### ISSUE TITLE
Docker: Owncloud wont show up in subdomain

### ISSUE THREAD

**Issue by JamesM92** [jc21/nginx-proxy-manager#1410]
I posted on the reddit page, but my request for assistance was auto removed as spam after 24 hours.
-https://www.reddit.com/r/nginxproxymanager/comments/povp9v/docker_nginx_proxy_manager_owncloud_dns_can_see/

**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**
-Upstream server wont show up on subdomain no matter the internal IP i tell it to use
-Can't issue subdomain ssl even with dns challenge, even though the dns challenge works for the main site.

**Nginx Proxy Manager Version**
v2.9.9

**To Reproduce**
NPM docker compose
```
version: "2" #version of docker compose you want to use


networks:
  frontend:
    external:
      name: nginx_frontend
  backend:
    external:
      name: nginx_backend

  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/dev-disk-by-label-Archive/portainer/Nginx/_data/data

  ssl:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/dev-disk-by-label-Archive/portainer/Nginx/_data/ssl

  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/dev-disk-by-label-Archive/portainer/Nginx/_data/db

services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - data:/data
      - ssl:/etc/letsencrypt
    networks:
      - frontend
      - backend
    depends_on:
      - db
      
  db:
    image: jc21/mariadb-aria:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
```

Owncloud Docker Compose
```
version: "3"

networks:
  frontend:
    external:
      name: nginx_frontend
  backend:
    external:
      name: nginx_backend

volumes:
  files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/dev-disk-by-label-Archive/portainer/OwnCloud/_data
      
  mysql:
    driver: local
    #driver_opts:
      #type: "cifs"
      #device: "//192.168.0.###/portainer/OwnCloud/_data/mysql/"
      #o: "uid=0,username=portainer,password=########"
  redis:
    driver: local
    #driver_opts:
      #type: "cifs"
      #device: "//192.168.0.###/portainer/OwnCloud/_data/redis/"
      #o: "uid=0,username=portainer,password=#######"


services:
  owncloud:
    image: owncloud/server:10.7.0
    container_name: owncloud_server
    restart: unless-stopped
    #ports:
      #- 8080:8080
    expose:
      - 8080
    depends_on:
      - mariadb
      - redis
    environment:
      - OWNCLOUD_DOMAIN=localhost
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=########
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data
    networks:
      - frontend
      - backend


  mariadb:
    image: mariadb:10.5
    container_name: owncloud_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:6
    container_name: owncloud_redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data
    networks:
      - backend
```

**Expected behavior**
For the view i get from accessing the service directly to appear when accessing the subdomain.

**Screenshots**
### Domain Setup
![image](https://user-images.githubusercontent.com/36548759/133663176-7ed87fe6-9ecb-4549-96e8-df28e1b0a73a.png)
![image](https://user-images.githubusercontent.com/36548759/133663216-cc65f513-9508-49ea-ba85-d8f8809459ca.png)
![image](https://user-images.githubusercontent.com/36548759/133663277-61efd565-7c6c-4fbe-9840-ba532cad8525.png)

### Subdomain Setup
![image](https://user-images.githubusercontent.com/36548759/133663459-ec567fcf-e8d6-43d4-8a5a-58455f2c1b21.png)
![image](https://user-images.githubusercontent.com/36548759/133663524-794e06d7-738e-46ba-8956-7ebf6d691879.png)
![image](https://user-images.githubusercontent.com/36548759/133663600-08c944f5-436c-4d89-930e-06b5ee5e49a6.png)

**Operating System**
Open Media Vault 5 on ASUS WS C246M PRO uATX Server Motherboard

**Additional context**
Ive tried searching for any tutorials or guides to trouble shoot but i havent been able to find any that resolved the issue.

Things Attempted:
-Creating a dedicated front end network, both with subnets 192.168.64.0, and 172.10.0.0
-In proxy host specifying as the hostname / ip
_     _owncloud-server
_     _owncloud
_     _192.168.64.4 (ip on front end entwork)
_     _192.168.0.(hostip)
_     _172.10.0.4 (ip on front end network)
-changing the owncloud domain to both cloud.mydomain.com and mydomain.com
