### ISSUE TITLE
MariaDB Issues

### ISSUE THREAD

**Issue by Conmyster** [jc21/nginx-proxy-manager#146]
Hello, so I am using the latest linuxserver/mariadb container at the time of writing this but when I run the nginx-proxy-manager (with config)  it starts but then gets the following error:

`create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1`

Any Ideas on how to resolve this?

**Comment by jc21** [comment]
I really doubt you're using the latest maria db at all. Json field support was added in 10.2.7.

**Comment by Conmyster** [comment]
It seems that I need to get a new Pi as the current one is Arm32 bit and newer versions of MariaDB aren't available for it.

**Comment by talondnb** [comment]
Just wanted to post this as I managed to get it running on a RPI 3B:

```
version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      # Public HTTP Port:
      - 80:80
      # Public HTTPS Port:
      - 443:443
      # Admin Web Port:
      - 81:81
    volumes:
      # Make sure this config.json file exists as per instructions above:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: yobasystems/alpine-mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "password"
    volumes:
      - ./data/mysql:/var/lib/mysql

```
