### ISSUE TITLE
how to changer the port in environment

### ISSUE THREAD

**Issue by q123458384** [jc21/nginx-proxy-manager#1491]
I would like to start npm with docker，but IPV6 is not supported in my docker with bridge mode.
IPV6 is only supported in  host mode，but the port “80" "443" are occupied.
how can I changer the port in  environment?
thanks!

**Comment by chaptergy** [comment]
The docker-compose file contains a port section, where there are port pairs (e.g. `80:80`) where the first number before the colon is the port used on the host, and the second number is the port inside the container. Just change the first value to use any port you want. But remember, if you do not use standard ports you will have to access your proxied apps including your non-custom port. For example when you use port `3080` instead of `80` you can only access your app at `sub.example.com:3080` instead of `sub.example.com`.

Snipped from example yml file for some context:
```yml
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '<http-port>:80'
      - '81:81'
      - '<https-port>:443'
    ...
```
