### ISSUE TITLE
Allow DNS name for proxy host, not just IP address

### ISSUE THREAD

**Issue by aim29** [jc21/nginx-proxy-manager#16]
Hello,

I wonder if it would be possible to allow the use of DNS names, rather than just IP addresses, when defining proxy hosts? This would be useful, for example, for proxying to Docker containers on the same network, rather than having to expose ports/assign static IPs using a custom network.

Thanks in advance, and thanks for your work on this project - it has helped me out immensely!

**Comment by jc21** [comment]
Definitely would be preferred yes, due to the way nginx proxy currently works it's just not that simple. Not impossible though, just needs more effort :)

**Comment by MisterCyp** [comment]
Hi Everyone,

I have a problem to assign static ip. My reverse proxy works when i don't use static ip.

Here are my files:

```
version: "3"
      
services:
  nginx:
    image: jc21/nginx-proxy-manager:2
    restart: always
    container_name : nginx-proxy-manager
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /home/cyprien/config/nginx-proxy-manager/config.json:/app/config/production.json
      - /home/cyprien/config/nginx-proxy-manager/data:/data
      - /home/cyprien/config/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - db_nginx
      
  db_nginx:
    image: mariadb
    restart: always
    container_name : mariadb_nginx
    environment:
      MYSQL_ROOT_PASSWORD: "**********"
      MYSQL_DATABASE: "nginxproxymanager"
      MYSQL_USER: "cyprien"
      MYSQL_PASSWORD: "*******************"
    volumes:
      - /home/cyprien/config/mariadb/data/mysql:/var/lib/mysql
  
  rutorrent:  
    image: xataz/rtorrent-rutorrent
    restart: always
    container_name: rutorrent
    environment:
      - WEBROOT=/
      - UID=1000
      - GID=1000
    ports:
      - 45000:45000
      - 45000:45000/udp
    volumes:
      - /home/cyprien/nextcloud/data/cyprien/files/Telechargements/:/data
      - /home/cyprien/config/rutorrent/:/config
    networks:
     test:
       ipv4_address: 172.28.0.10
   
  emby:
    image: xataz/emby
    restart: always
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - /home/cyprien/nextcloud/data/cyprien/files/Telechargements/:/Media 
      - /home/cyprien/config/emby/:/embyData 
    networks:
     test:
       ipv4_address: 172.28.0.20
      
  nextcloud:
    restart: always
    image: wonderfall/nextcloud
    container_name: nextcloud
    depends_on:
      - nextcloud-db          # If using MySQL
    environment:
      - UID=1000
      - GID=1000
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=Europe/Paris
      - ADMIN_USER=cyprien            # Don't set to configure through browser
      - ADMIN_PASSWORD=*************# Don't set to configure through browser
      - DOMAIN=******************
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=**************
      - DB_HOST=nextcloud-db
    volumes:
      - /home/cyprien/nextcloud/data:/data
      - /home/cyprien/config/nextcloud:/config
      - /home/cyprien/nextcloud/apps:/apps2
      - /home/cyprien/nextcloud/themes:/nextcloud/themes
      
    networks:
      test:
        ipv4_address: 172.28.0.30

  nextcloud-db:
    restart: always
    image: mariadb:10
    container_name: nextcloud-db
    volumes:
      - /home/cyprien/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=******************
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=***************
      
      
networks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
```
my reverse proxy:
![Uploading image.png…]()

IPs of my containers:
```
172.28.0.20 cyprien_emby_1
172.18.0.5 nginx-proxy-manager
172.28.0.30 nextcloud
172.18.0.4 mariadb_nginx
172.18.0.3 nextcloud-db
172.28.0.10 rutorrent
```

And when I try to reach a page, I got 504 Gateway Time Out.
Without the static ip adress it works.

Thank you for your help.

Cyprien
