### ISSUE TITLE
Cannot connect to the DB when it is on another host.

### ISSUE THREAD

**Issue by CrashyBang** [jc21/nginx-proxy-manager#198]
**Checklist**
Yes I am using the latest version.

**Describe the bug**
The database connection is refused when the containers are separate.

**To Reproduce**
I need to run the app on a docker `macvlan` so I have adjusted the example to be like so:

```
version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    networks:
      br0:
        ipv4_address: 192.168.1.253
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    #environment:
    # if you want pretty colors in your docker logs:
    #- FORCE_COLOR=1
  db:
    #image: mariadb:latest
    build: .
    restart: always
    networks:
      br0:
        ipv4_address: 192.168.1.252
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "password"
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:  br0:
    external: true
```

This is the Dockerfile I am using for the DB:

```
FROM mariadb:latest

LABEL maintainer="user@email.com"

RUN apt-get update && apt-get upgrade -y

# UPDATE BIND ADDRESS TO ALLOW REMOTE ACCESS (USE A FIREWALL TO MANAGE TRAFFIC)
RUN sed -Ei 's/#bind-address\s+=\s+127.0.0.1/bind-address=0.0.0.0/g' /etc/mysql/my.cnf

EXPOSE 3306
```

And here is my `config.json`:

```json
{
  "database": {
    "engine": "mysql",
    "host": "192.168.1.252", // db when using networks (below)
    "name": "npm",
    "user": "npm",
    "password": "password",
    "port": 3306
  }
}
```

I also tried putting the both containers on a `local` bridge network and then connecting to the DB like usual (without adjusting the `bind-address`) same issue.

**Expected behavior**
I am confident that at least one of these methods should have allowed a remote connection, I based this directly on the MariaDB docs https://mariadb.com/kb/en/library/configuring-mariadb-for-remote-client-access/

**Operating System**
- Unraid 6.6.7

**Additional context**
I can't think of anything else, but let me know if you can think of anything.

```
docker-compose version 1.23.2, build 1110ad01
```
