### ISSUE TITLE
No admin interface running with docker-coimpose on non-default ports

### ISSUE THREAD

**Issue by toxic0berliner** [jc21/nginx-proxy-manager#21]
Hello,
I'm using my NAS which is already busy for the moment on port 80 and 443 to run this with docker-compose.
I get it up, but sadly nothing answers on port 81...
I got a terminal inside the container and nothing is bound to port 81.

Here is my docker-compose (note the port binding, also tried with 8081:81 first...): 
```
version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:2
    restart: always
    ports:
      - 8080:80
      - 81:81
      - 8443:443
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "XXX"
      MYSQL_DATABASE: "nginxproxymanager"
      MYSQL_USER: "nginxproxymanager"
      MYSQL_PASSWORD: "YYY"
    volumes:
      - ./data/mysql:/var/lib/mysql
```

and my config.json:
```
{
  "database": {
    "engine": "mysql",
    "host": "127.0.0.1",
    "name": "nginxproxymanager",
    "user": "nginxproxymanager",
    "password": "YYY",
    "port": 3306
  }
}

```

When I start it it looks fine : 
```
$ sudo docker-compose up
Starting nginxproxymanager_db_1 ...
Starting nginxproxymanager_db_1 ... done
Recreating nginxproxymanager_app_1 ...
Recreating nginxproxymanager_app_1 ... done
Attaching to nginxproxymanager_db_1, nginxproxymanager_app_1
db_1   | WARNING: no logs are available with the 'db' log driver
app_1  | WARNING: no logs are available with the 'db' log driver
```

But the app container spits an awefull lot of errors : 
```
2018-10-05 18:03:08,stdout,[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

2018-10-05 18:03:09,stdout,[s6-init] ensuring user provided files have correct perms...exited 0.
2018-10-05 18:03:09,stdout,[fix-attrs.d] applying ownership & permissions fixes...

2018-10-05 18:03:09,stdout,[fix-attrs.d] done.


2018-10-05 18:03:09,stdout,[cont-init.d] executing container initialization scripts...

2018-10-05 18:03:09,stdout,[cont-init.d] done.

2018-10-05 18:03:09,stdout,[services.d] starting services

2018-10-05 18:03:09,stdout,[services.d] done.

2018-10-05 18:03:11,stdout,[10/5/2018] [6:03:11 PM] [Global  ] › ✖  error                        connect ECONNREFUSED 127.0.0.1:3306
```
The last one keeps repeating every second as you can guess...

Opening a terminal inside the container gives a hint : 
```
[root@docker-a98e0ffeecf8:/app]# ifconfig -a                                                                     
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500                                                       
        inet 172.18.0.3  netmask 255.255.0.0  broadcast 0.0.0.0                                                  
        ether 02:42:ac:12:00:03  txqueuelen 0  (Ethernet)                                                        
        RX packets 18706  bytes 42735084 (40.7 MiB)                                                              
        RX errors 0  dropped 0  overruns 0  frame 0                                                              
        TX packets 12506  bytes 853944 (833.9 KiB)                                                               
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0                                               
                                                                                                                 
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536                                                                     
        inet 127.0.0.1  netmask 255.0.0.0                                                                        
        loop  txqueuelen 1  (Local Loopback)                                                                     
        RX packets 5084  bytes 310909 (303.6 KiB)                                                                
        RX errors 0  dropped 0  overruns 0  frame 0                                                              
        TX packets 5084  bytes 310909 (303.6 KiB)                                                                
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0                                               
                                                                                                                 
sit0: flags=128<NOARP>  mtu 1480                                                                                 
        sit  txqueuelen 1  (IPv6-in-IPv4)                                                                        
        RX packets 0  bytes 0 (0.0 B)                                                                            
        RX errors 0  dropped 0  overruns 0  frame 0                                                              
        TX packets 0  bytes 0 (0.0 B)                                                                            
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0                                               
                                                                                                                 
[root@docker-a98e0ffeecf8:/app]# netstat -tulpn                                                                  
Active Internet connections (only servers)                                                                       
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name                 
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      191/nginx: master p              
tcp        0      0 127.0.0.11:39794        0.0.0.0:*               LISTEN      -                                
tcp        0      0 0.0.0.0:9876            0.0.0.0:*               LISTEN      191/nginx: master p              
udp        0      0 127.0.0.11:55989        0.0.0.0:*                           -                                
```

Nothing listening on port 81 or port 443...
I do get the "Congratulations" page on port 8080 from another computer...

My NAS is a Synology DS918+ running an intel x86 processor, so I think I didn't have to go for the arm version there.

Oh, and I did start it with the configfile (it's properly mounted in the /app/config/production inside the container) and I had an empty data and letsencrypt folder as well.

Will appreciate any help, will "docker compose down" for the moment but I'll be able to spin it up again if you like further checks.

Thanks in advance,
Regards,
Toxic.

**Comment by jc21** [comment]
I can see that your config file lists the host as 127.0.0.1 but the docker
compose file doesn’t expose a port for MySQL. You can either change the
host name to “db” in your config since that’s the name of the service, or
add port: 3306:3306 to the fb docket compose section.

**Comment by jc21** [comment]
**EDIT: reposting with examples**

I can see that your config file lists the host as 127.0.0.1 but the docker
compose file doesn’t expose a port for MySQL. You can either change the
host name to “db” in your config since that’s the name of the service

```json
{
  "database": {
    "engine": "mysql",
    "host": "db",
    "name": "nginxproxymanager",
    "user": "nginxproxymanager",
    "password": "YYY",
    "port": 3306
  }
}
```

or add port: 3306:3306 to the db docker compose section:

```yml
version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:2
    restart: always
    ports:
      - 8080:80
      - 81:81
      - 8443:443
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "XXX"
      MYSQL_DATABASE: "nginxproxymanager"
      MYSQL_USER: "nginxproxymanager"
      MYSQL_PASSWORD: "YYY"
    volumes:
      - ./data/mysql:/var/lib/mysql
```
