### ISSUE TITLE
Change instructions for RPI

### ISSUE THREAD

**Issue by skluthe** [jc21/nginx-proxy-manager#212]
The current docker-compose doesn't include the correct image for a raspberry pi. The official Mariadb image doesn't have an arm7 option in the manifest. The correct one to use for a raspberry pi is linuxserver/mariadb. I don't think you need to change it in the docker-compose file but it may be a good idea to include that info in the read-me.

**Comment by skluthe** [comment]
This is incorrect. Sorry about that. The default instructions will not work if you're running standard 32 bit raspbian.

**Comment by khannurien** [comment]
Just use `webhippie/mariadb:latest` as NPM requires MariaDB 10.2 for JSON fields.

```
  nginx:
    depends_on:
      - mariadb
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443"
    volumes:
      - ./config.json:/app/config/production.json
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt

  mariadb:
    image: webhippie/mariadb:latest
    restart: always
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_backup:/var/lib/backup
    environment:
      - MARIADB_ROOT_PASSWORD=m0nM0td3p4553r007!
```
