### ISSUE TITLE
SQL Syntax Error

### ISSUE THREAD

**Issue by skluthe** [jc21/nginx-proxy-manager#213]
Getting this error when trying to start up on a raspberry pi:
```
migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1

```
using linuxserver/mariadb:arm32v7-110.3.18mariabionic-ls37 for my database as the one included doesn't have the manifest setup correctly on the RPI 4.

Here is my config.json:
```
{
  "database": {
    "engine": "mysql",
    "host": "db",
    "name": "nginxdb",
    "user": "nginxusr",
    "password": "password",
    "port": 3306
  }
}
```
Here is my docker-compose.yml:
```
version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    environment:
    # if you want pretty colors in your docker logs:
    - FORCE_COLOR=1
  db:
    image: linuxserver/mariadb:arm32v7-110.3.18mariabionic-ls37
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "nginxdb"
      MYSQL_USER: "nginxusr"
      MYSQL_PASSWORD: "password"
    volumes:
      - ./data/mysql:/var/lib/mysql
```
