### ISSUE TITLE
Cannot generate letsencrypt certificate "Internal Error"

### ISSUE THREAD

**Issue by dbrosy** [jc21/nginx-proxy-manager#226]
Ok I don't understand why this doesn't work.

I have created nginx proxy manager with 80, 81 and 443 open to public. I am trying to secure dashboard on port 81 with proxy.<example.com> (<example.com> not my real domain)

![image](https://user-images.githubusercontent.com/17326295/68071549-8f8dc000-fdcf-11e9-8e5a-c8b428c3e583.png)

I can browse to http(s)://proxy.example.com and see login page. 
If I try to create an ssl cert for my domain i get "internal error" with following in logs:

![image](https://user-images.githubusercontent.com/17326295/68071662-a7197880-fdd0-11e9-9f74-3efef9b23aca.png)

#### docker-compose.yml:

```
version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:2.0.14
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    networks:
      - proxy
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    environment:
    # if you want pretty colors in your docker logs:
    - FORCE_COLOR=1
  db:
    image: mariadb:10.3
    container_name: nginx-db
    restart: always
    ports:
      - 3306:3306    
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - proxy
    volumes:
      - ./data/mysql:/var/lib/mysql
#  portainer:
#    image: portainer/portainer
#    container_name: portainer
#    command: -H unix:///var/run/docker.sock
#    restart: always
#    environment:
#      - VIRTUAL_HOST=${VIRTUAL_HOST}
#    networks:
#      - proxy
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data

networks:
  proxy:

#volumes:
#  portainer_data:
```

#### config.json

```
{
  "database": {
    "engine": "mysql",
    "host": "db",
    "name": "npm",
    "user": "npm",
    "password": "npm",
    "port": 3306
  }
}
```

The error seems to be related to /.well-known/acme-challenge/...

What am I doing wrong?

I would like to the create certs for any domain I point to my proxy
