### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by talondnb** [jc21/nginx-proxy-manager#298]
image: jc21/nginx-proxy-manager:latest

**Describe the bug**
npm app doesn't boot, with the logs showing:
standard_init_linux.go:211: exec user process caused "exec format error"

**To Reproduce**
docker-compose.yaml (previously worked fine until recent update)

```
version: "3.5"

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=10.10.10.100,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: ":/volume1/Config/npm/data"
  letsencrypt:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=10.10.10.100,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: ":/volume1/Config/npm/letsencrypt"

services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      # Make sure this config.json file exists
      - /mnt/config/npm/config.json:/app/config/production.json
      - data:/data
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: yobasystems/alpine-mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "password"
    volumes:
      # Does not work on an NFS volume
      - /home/xxx/npm/data/mysql:/var/lib/mysql
```

**Expected behavior**
npm app boots normally

**Operating System**
Hypriot docker image on Pi4
