### ISSUE TITLE
mydomain.com has rejected the connection.

### ISSUE THREAD

**Issue by marrobHD** [jc21/nginx-proxy-manager#329]
**Checklist**
- [x] Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
- [x] Are you sure you're not using someone else's docker image?
- [x] If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?

**Describe the bug**
- When I try to go to https://mydomain.com, I get the error message https://mydomain.com has rejected the connection.
- Nginx Proxy Manager version: v2.2.0

**To Reproduce**
1. Go to 'Proxy Hosts' and select a domain
2. Go to 'SSL' tab and select request new SSL Certificate
3. Click on 'save'
4. Point browser to https://mydomain.com and see:
```
The website is unavailable
https://mydomain.com has rejected the connection.
ERR_CONNECTION_REFUSED
```

**Expected behavior**
It should show the web page with a closed lock

**Screenshots**
![image](https://user-images.githubusercontent.com/29308361/76687371-889b7780-6623-11ea-9a95-2c092a4603e6.png)

**Operating System**
- (host ) Ubuntu 19.10 LXC Container with keyctl and nesting enabled
- (client) Win10 Pro

**Additional context**
- Docker version 19.03.6, build 369ce74a3c
- Chrome version 80.0.3987.132 (Official Build) (64-Bit)

**Comment by miguelwill** [comment]
validate if port 80 and 443 are correctly allowed in your iptables or docker-compose configuration and mapped ports

**Comment by marrobHD** [comment]
Checked. All looks right

**Comment by marrobHD** [comment]
Checked. All looks good.
```yaml
#docker-compose.yaml
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:10.4'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
```

```
root@nginx-proxy-manager:/home# iptables -S                                        -P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-ISOLATION-STAGE-2
-N DOCKER-USER
-A INPUT -i lo -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -p tcp -m tcp --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m multiport --dports 80,443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o br-fc37d6a16a53 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-fc37d6a16a53 -j DOCKER
-A FORWARD -i br-fc37d6a16a53 ! -o br-fc37d6a16a53 -j ACCEPT
-A FORWARD -i br-fc37d6a16a53 -o br-fc37d6a16a53 -j ACCEPT
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 80 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 443 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m multiport --dports 80,443 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A DOCKER -d 172.18.0.3/32 ! -i br-fc37d6a16a53 -o br-fc37d6a16a53 -p tcp -m tcp --dport 443 -j ACCEPT
-A DOCKER -d 172.18.0.3/32 ! -i br-fc37d6a16a53 -o br-fc37d6a16a53 -p tcp -m tcp --dport 81 -j ACCEPT
-A DOCKER -d 172.18.0.3/32 ! -i br-fc37d6a16a53 -o br-fc37d6a16a53 -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i br-fc37d6a16a53 ! -o br-fc37d6a16a53 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o br-fc37d6a16a53 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
```

**Comment by miguelwill** [comment]
Okay, the port seems to be allowed in both the mapping and the iptables that the docker manages
the computer is on a local network?
if you try "telnet ip-host 80" can you establish the connection?
you should be able to connect if you are in the same local network, and after checking that, try remote access

**Comment by miguelwill** [comment]
you can try to define a docker network in the docker-compose.yml file so that the network is not the default bridge

add to the statement of services:

> networks:
>       - pmanager


and add to the end of the file 

> networks:
>   pmanager:
>     name: pmanager

**Comment by marrobHD** [comment]
Telnet works on both ports.
Thats now my config:


```
root@nginx-proxy-manager:/home# cat docker-compose.yml
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
         - pmanager
  db:
    image: 'jc21/mariadb-aria:10.4'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
         - pmanager

networks:
    pmanager:
```
Still ERR_CONNECTION_REFUSED
