### ISSUE TITLE
Upgrade Instructions?

### ISSUE THREAD

**Issue by mikepruett3** [jc21/nginx-proxy-manager#331]
My appoligies if this has been documented somewhere else, but I did look at both all of the Issues and documentation from the site.

I am currently running v2.0.14, which was built and started via docker-compose...and I was wondering what I would need to do to upgrade to the latest version?

docker-compose.yml
```yaml
# WARNING: This is a DEVELOPMENT docker-compose file, it should not be used for production.
version: "2"
services:
  app:
    image: jc21/nginx-proxy-manager-base:latest
    ports:
      - 80:80
      - 81:81
      - 43:443
    environment:
      - NODE_ENV=development
      - FORCE_COLOR=1
    volumes:
      - ./data:/data
      - ./data/letsencrypt:/etc/letsencrypt
      - .:/app
      - ./rootfs/etc/nginx:/etc/nginx
    working_dir: /app
    depends_on:
      - db
    links:
      - db
    command: node --max_old_space_size=250 --abort_on_uncaught_exception node_modules/nodemon/bin/nodemon.js
  db:
    image: jc21/mariadb-aria
    environment:
      MYSQL_ROOT_PASSWORD: "<redacted>"
      MYSQL_DATABASE: "<redacted>"
      MYSQL_USER: "<redacted>"
      MYSQL_PASSWORD: "<redacted>"
    volumes:
      - ./config/my.cnf:/etc/mysql/conf.d/npm.cnf
      - ./data/mysql:/var/lib/mysql
```
