### ISSUE TITLE
Help needed to set up proxy host

### ISSUE THREAD

**Issue by Zhaobab** [jc21/nginx-proxy-manager#490]
Hello everyone

Thanks for this awesome tools! I'm trying to set up it but facing issues.
My ISP block 80 and 443 ports, then I want to use 5443.
I wish to redirect my https://proxmox.domain.me:5443 to http://192.168.1.8:8006 and https://gotify.domain.me:5443 to http://192.168.1.11:80

1. I forwarded 5443 port to my 192.168.1.12 NPM server.
2. My NPM docker-compose looks like this:

```
version: "3"
 services:
   app:
     image: jc21/nginx-proxy-manager:latest
     restart: always
     ports:
       # Nginx Proxy Manager console port
       - '81:81'
       # HTTP/HTTPS, 80 is used by Let's Encrypt.
       - '80:80'
       - '443:443'
       # HTTPS workaround because 443 blocked
       - '5443:5443'
     environment:
       - 'DISABLE_IPV6=true'
     volumes:
       - ./config.json:/app/config/production.json
       - ./data:/data
       - ./letsencrypt:/etc/letsencrypt
   db:
     image: jc21/mariadb-aria:10.4
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 'npm'
       MYSQL_DATABASE: 'npm'
       MYSQL_USER: 'npm'
       MYSQL_PASSWORD: 'npm'
     volumes:
       - ./data/mysql:/var/lib/mysql
```
3. I created 2 proxy hosts with these config
![image](https://user-images.githubusercontent.com/6453724/86598779-361a0880-bfd0-11ea-8a3d-7dbc8b209499.png)
Nothing in Custom Location, SSL use custom imported LE certificate.

**Issue**:
With this configuration, nothing respond on link https://proxmox.domain.me:5443
I guess it's because the nginx server does not listen on 5443 port ? I tried to add `listen 5443 ssl http2;` in Advanced > Custom Nginx Configuration, then it works for the 1st proxy but not the other one (which redirect to the 1st one).

Any thought about how configure this properly? I also tried to forward 5443 to 433 in Docker but gives me weird SSL issues in Firefox with a NPM "Dummy Certificate"

Thank you!
