### ISSUE TITLE
Feature request: Website host

### ISSUE THREAD

**Issue by TheBlueKingLP** [jc21/nginx-proxy-manager#58]
I would like to see website host in this docker
It should be like the proxy host, but instead of asking you for the Scheme,Forward Hostname / IP and Forward Port, it should ask for a path for the website contents.
It should also support php7 for hosting php files.

**Comment by brandonkal** [comment]
I can see adding support for static sites. This would be a nice feature. Setting fast-cgi parameters may even be a nice enhancement.

But executing php, ruby, node, etc should not be in the scope of this project. It should be done in its own docker container. Just add it to your docker-compose file. Or consider using [Caddy](https://caddyserver.com) @TheBlueKingLP  with a php backend container.

**Comment by jc21** [comment]
Yep :) I agree that if I open the floodgates with PHP support, I'd have to do it for others as well. Not to mention that PHP with Nginx requires yet another process to be running in the background and I'm not sure about other cgi handlers but I'd guess they might need them too. This doesn't make the proxy a lightweight solution.

I can see value in adding basic html support though. Seems overkill to spin up another docker container just to spit out plain text html files. Adding this feature costs nothing.

In future it might be possible to build spin-off docker images that extend the base functionality, so you might have `latest`, `latest-php`, `latest-ruby` etc and leave the choice up to the end user rather than trying to accommodate everyone. But don't hold your breath on that.

**Comment by ptr727** [comment]
Yes please, static site, mapped in container path.

**Comment by brentco** [comment]
It would be great! This is the thing I'm missing the most. I started up this image and I quickly realized "wait a minute, I don't have that many proxies". I have a wordpress website, a simple domain that makes a folder browseable, and some subdomains that are proxies but yeah... I'm conflicted now because the bulk of my configuration wouldn't be managed by the UI :(

So please, consider adding this website host feature, optionally with the spin-off docker images you mentioned! Let me know if you require assistance!

**Comment by lopugit** [comment]
At first I wanted static sites to be supported but I get why they're not, it would mean your nginx container would need to have a bunch of volumes attached to it for each static site, or just 1 volume for all of them, and that defeats the modular purpose of docker.

What I'm doing is running this, proxying to a certain ip, which then runs another deployment of an nginx container with 1 static site in it, so each static site gets its own nginx process and ip, effectively turning static sites into ip address sites. 

Now then yeah you have to manage that config through text but managing one site's config through files is alright compared to managing numerous load-balanced proxies on your nginx-proxy-manager instance.

Just my thoughts

**Comment by realJoshByrnes** [comment]
I've been doing this following for quite some time in my 404 hosts to enable some simple static hosting

```
root /var/www/html;

location / {
  index index.html index.htm;
}
```
Note: This will likely break your preset settings such as "Force SSL" settings for this host. (although certificates will work fine)

### For PHP support

My docker compose is slightly different, I've added PHP FPM in a seperate container, and I'm exposing the host's /var/www directory to both the app and php container (the directory could be anything, but this is what I chose to use)
```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - /var/www:/var/www
    depends_on:
      - db
    links:
      - php
  php:
    image: php:8-fpm
    restart: always
    volumes:
      - /var/www:/var/www
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
```

Finally, for those hosts **that you would like to enable PHP on**, you should use something like the following in the advanced tab
```
root /var/www/html;

location / {
  index index.php index.html index.htm;
}

location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass php:9000;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
}
```

I quite like that I can mix and match PHP and non-PHP sites quite easily on the same host. There may be a more elegant solution but this is what I've been using for quite some time, so thought I'd share it.
