### ISSUE TITLE
Getting Error when Arm64/Odroid C4 - OMV5 - Debian Stretch 64

### ISSUE THREAD

**Issue by TheFlatworm** [jc21/nginx-proxy-manager#581]
OMV5 Debian Stretch64 for arm64 Odroid C4 board

Creating config.json and docker-compose.yaml per installation instructions.  When docker-compose up -d is run I get the following error:

```
ERROR: Failed to program FILTER chain: iptables failed: iptables --wait -I FORWARD -o br-bd9843adfdb5 -j DOCKER: iptables v1.8.2 (nf_tables):  RULE_INSERT failed (Invalid argument): rule in chain FORWARD
 (exit status 4)

```

Config:
```
{
  "database": {
    "engine": "mysql",
    "host": "db",
    "name": "DBNAME",
    "user": "DBUSERNAME",
    "password": "DBPASSWORD",
    "port": 3306
  }
```
docker-compose:
```
version: '2'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - './config.json:/app/config/production.json'
      - './data:/data'
      - './letsencrypt:/etc/letsencrypt'
    depends_on:
      - db
  db:
    image: 'yobasystems/alpine-mariadb:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: npman
      MYSQL_DATABASE: npman
      MYSQL_USER: npman
      MYSQL_PASSWORD: pasmuqks
    volumes:
      - './data/mysql:/var/lib/mysql'

```
