### ISSUE TITLE
Access from Global via https is not working

### ISSUE THREAD

**Issue by GEkuL** [jc21/nginx-proxy-manager#673]
I've set up ampache server and connected it to domain via NPM. Everything was working without SSL: I could access the service from the Global.
After the turning SSL and trying https connection, the page doesn't show up. Yet without https connection from Global is still working fine.
Moreover https is working fine from the local network. But from the global the service is not uploading((((

Could you help me please!
Got the issue since the first installation of docker. Thought it's kind of bug. But it looks like the problem on my server. And I totally don't know what causes the problem.

Firewall is seemed to be disabled.
Possibly it could be the router, but I can't imagine how can it block SSL traffic directed to global internet...

**Comment by Wadera** [comment]
are you sure that you forwarding both ports on your router?
80 for http
443 for https

**Comment by GEkuL** [comment]
@Wadera yeps
I'm forwarding both ports

Could it be some docker's settings since I use the NPM in container?

**Comment by Wadera** [comment]
I think that everyone using NPM in docker container as that's how this tool is officially shipped ;)

make sure that you specified both ports under `docker-compose.yml`

**Example docker composer config:**
**80:** for http prox support
**81:** for NMP panel
**443:** for https proxy support
**2500-3000:** for forwarding ports for other applications under Streams 

Of course you need to forward the same ports on your Router to your docker node machine IP

```
version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
      - 2500-3000:2500-3000/tcp
      - 2500-3000:2500-3000/udp
    volumes:
      - /somewhere/on/your/local/storage/proxy/config.json:/app/config/production.json
      - /somewhere/on/your/local/storage/proxy/data:/data
      - /somewhere/on/your/local/storage/proxy/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    environment:
    # if you want pretty colors in your docker logs:
    - FORCE_COLOR=1
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "yoursecretroodpassword"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "yoursecretpassword"
    volumes:
      - /somewhere/on/your/local/storage/proxy/data/mysql:/var/lib/mysql
```

And then to start:
```
# docker-compose up -d
```

Of if you rewrite your already existing docker compose config:
```
# docker-compose down && docker-compose up -d
```
