### ISSUE TITLE
Forward real remote IP to docker containers

### ISSUE THREAD

**Issue by Sanksari12** [jc21/nginx-proxy-manager#674]
Hi,

I am running nginx-proxy-manager version v2.6.1 on Ubuntu with Docker.
I use nginx-proxy-manager to forward all incoming web traffic to the corresponding docker container on the host machine. Nextcloud for example.

My issue is, that I cannot get nginx to forward the true client remote IP to the Nextcloud container (or any other container for that matter).

The docker networking looks like this:

nginx-proxy-manager_app is attached to two networks: 
bridge (IP 172.17.0.4, GW 172.17.0.1)
nginxproxymanager_default (IP 192.168.16.3, GW 192.168.16.1)

the Nextcloud container is attached to:
bridge (IP 172.17.0.3, GW 172.17.0.1)
nextcloud_default (IP 192.168.32.3, GW 192.168.32.1)

When I look in the access logs for my nextcloud container, I see that log in attempts are logged as coming from the source IP 172.17.0.4. Which is not my real IP address and weirdly also not the IP of the nginx container as I would have expected.
My question now is: What exact parameters do I have to enter into the nextcloud proxy host's "Custom Nginx Configuration" field? Or do I need to change the networking settings in docker?
I tried several fixes from other sites, but none of them seem to work, as I still get the 172.17.0.4 IP shown as the source.

Thank you very much in advance for helping me out!
If you need any further infos about my setup, I'll be happy to supply!

**Comment by poims-dev** [comment]
I have the same problem.
I tried changing the network to host (like as #issuecomment-464364484) , emptying the contents of the ip_range file in the container and restart nginx in the running container, but it didn't work.

**Comment by bugiii** [comment]
I have the same problem.
I tried changing the network to host like as https://github.com/jc21/nginx-proxy-manager/issues/41#issuecomment-464364484 , emptying the contents of the ip_range file in the container and restart nginx in the running container, but it didn't work.

**Comment by bugiii** [comment]
I'm working with Synology's Docker.
I don't know if the other environments are different, but at least the results in Synology are:
If the network is not in host mode, it seems that you cannot get an external real ip.
It seems to be a route problem, and docker's default mode does not support the router role.
It seems to be a route problem, and that the router role is not supported in docker's default mode.
See: https://stackoverflow.com/questions/47537954/how-to-make-docker-container-see-real-user-ip

I gave up using `networks` of `docker-compose.yml` to connect to other containers and connected using a local ip such as 127.0.0.1:40080.

Please refer to the following settings.

```
# NPM
version: '3'
services:
  app:
    image:'jc21/nginx-proxy-manager:latest'
    ports:
      -'81:81'
      -'80:80'
      -'443:443'
    volumes:
      -./config.json:/app/config/production.json
      -./data:/data
      -./letsencrypt:/etc/letsencrypt
    network_mode:'host' ### <--- THIS

# Code Server
version: '3.7'
services:
  code-server:
    image: codercom/code-server:latest
    container_name: code
    user: "0:0"
    volumes:
      -./project:/home/coder/project
      -./config:/root/.config
    ports:
      -127.0.0.1:40080:8080 ### <--- THIS
```

**Comment by Wadera** [comment]
**At first:** 
You need to add this into your Custom Nginx Configuration:
`add_header X-Frame-Options "SAMEORIGIN";`

**Example:**

![image](https://user-images.githubusercontent.com/407236/97346861-ebc0de00-1883-11eb-873d-cc079126f7ab.png)


Few others which can be useful to keep everything secured ;)

```
proxy_hide_header Upgrade;
proxy_hide_header X-Powered-By;
add_header Content-Security-Policy "upgrade-insecure-requests";
add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Cache-Control "no-transform" always;
add_header Referrer-Policy no-referrer always;
add_header X-Robots-Tag none;
```

If you like to limit access only for certain IP you (for example only for internal network , only over VPN etc):

```
satisfy any;
allow 172.27.226.7;
allow 172.17.0.3;
allow 192.168.0.1/15;
allow 10.230.189.0/24;
allow 172.0.0.1/8;
#allow YOUR_EXTERNAL_IPV4;
deny all;
```

**Second:**

On your Nextcloud server - you need to modify config to add trusted `trusted_proxies`
where `172.17.0.4` is your docker node IP

```
root@cloud ~# tail /var/www/nextcloud/config/config.php
...
  'mysql.utf8mb4' => true,
  'trusted_proxies' =>
  array (
    0 => '172.17.0.4',
  ),
  'forwarded_for_headers' =>
  array (
    0 => 'HTTP_X_FORWARDED_FOR',
  ),
);
```

**Comment by openaspace** [comment]
This for me doesn't works... 
I use nginx proxy manager with alpine linux under proxmox.. the internal host see only the proxy ip...
any help?

proxy_hide_header Upgrade;
proxy_hide_header X-Powered-By;
add_header Content-Security-Policy "upgrade-insecure-requests";
add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Cache-Control "no-transform" always;
add_header Referrer-Policy no-referrer always;
add_header X-Robots-Tag none;

**Comment by Wadera** [comment]
What web server you are using behind the proxy? It's Apache? Nginx? What app we talking about? It's Nextcloud as well?

**Comment by openaspace** [comment]
> What web server you are using behind the proxy? It's Apache? Nginx? What app we talking about? It's Nextcloud as well? 

This happen with any VPS behind.

Estia CP Web hosting
Nginx streaming server
FTP VPS
WebDAV VPS

Any request to the proxy reach the end VPS with the proxy IP instead the wan.

**Comment by Wadera** [comment]
As I've pointed in my first post in this discussion: 
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/674#issuecomment-717459734

To get IP properly proxed, it's a 2 step job:
1. Set NPM (Nginx Proxy Manager) to send origin IP to destination by adding: `add_header X-Frame-Options "SAMEORIGIN";` in advanced configuration
2. Learn web-server / application behind proxy to listen for origin IP and set "trusted proxy" as NPM IP, so it will read it and replace it in the logs.  

Example configuration for:
Apache: https://stackoverflow.com/questions/760283/apache-proxypass-how-to-preserve-original-ip-address
Nginx: https://serverfault.com/questions/837915/forwarding-real-remote-ip-to-proxied-server-with-nginx
Nextcloud: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html
etc. 

Every application / solution need to support it somehow and it should be described in docummentation.

**Comment by openaspace** [comment]
Really thank you for the support.
I will try.

> As I've pointed in my first post in this discussion: [#674 (comment)](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/674#issuecomment-717459734)
> 
> To get IP properly proxed, it's a 2 step job:
> 
>     1. Set NPM (Nginx Proxy Manager) to send origin IP to destination by adding: `add_header X-Frame-Options "SAMEORIGIN";` in advanced configuration
> 
>     2. Learn web-server / application behind proxy to listen for origin IP and set "trusted proxy" as NPM IP, so it will read it and replace it in the logs.
> 
> 
> Example configuration for: Apache: https://stackoverflow.com/questions/760283/apache-proxypass-how-to-preserve-original-ip-address Nginx: https://serverfault.com/questions/837915/forwarding-real-remote-ip-to-proxied-server-with-nginx Nextcloud: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html etc.
> 
> Every application / solution need to support it somehow and it should be described in docummentation.

**Comment by JustArtiom** [comment]
> As I've pointed in my first post in this discussion: [#674 (comment)](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/674#issuecomment-717459734)
> 
> To get IP properly proxed, it's a 2 step job:
> 
> 1. Set NPM (Nginx Proxy Manager) to send origin IP to destination by adding: `add_header X-Frame-Options "SAMEORIGIN";` in advanced configuration
> 2. Learn web-server / application behind proxy to listen for origin IP and set "trusted proxy" as NPM IP, so it will read it and replace it in the logs.
> 
> Example configuration for: Apache: https://stackoverflow.com/questions/760283/apache-proxypass-how-to-preserve-original-ip-address Nginx: https://serverfault.com/questions/837915/forwarding-real-remote-ip-to-proxied-server-with-nginx Nextcloud: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html etc.
> 
> Every application / solution need to support it somehow and it should be described in docummentation.

![image](https://user-images.githubusercontent.com/83312438/188701180-2ce27111-728c-41fb-92f2-ab07d1d3f46a.png)

Hmmm, in the latest version of NPM i see that set header wont work anymore in advanced configuration... any help in how to add a custom location '/' and add the header in the custom config? please :)?

**Comment by askareija** [comment]
> > As I've pointed in my first post in this discussion: [#674 (comment)](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/674#issuecomment-717459734)
> > To get IP properly proxed, it's a 2 step job:
> > 
> > 1. Set NPM (Nginx Proxy Manager) to send origin IP to destination by adding: `add_header X-Frame-Options "SAMEORIGIN";` in advanced configuration
> > 2. Learn web-server / application behind proxy to listen for origin IP and set "trusted proxy" as NPM IP, so it will read it and replace it in the logs.
> > 
> > Example configuration for: Apache: https://stackoverflow.com/questions/760283/apache-proxypass-how-to-preserve-original-ip-address Nginx: https://serverfault.com/questions/837915/forwarding-real-remote-ip-to-proxied-server-with-nginx Nextcloud: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html etc.
> > Every application / solution need to support it somehow and it should be described in docummentation.
> 
> ![image](https://user-images.githubusercontent.com/83312438/188701180-2ce27111-728c-41fb-92f2-ab07d1d3f46a.png)
> 
> Hmmm, in the latest version of NPM i see that set header wont work anymore in advanced configuration... any help in how to add a custom location '/' and add the header in the custom config? please :)?

Go to Custom Locations tab, press the cog/gear button and add your nginx configuration there
![Jepretan Layar 2022-12-07 pukul 10 46 15](https://user-images.githubusercontent.com/21377617/206083441-7a386761-3721-4c74-8c69-5dd245b0c037.png)

**Comment by dakiba** [comment]
I can't get it working too ...
I tried a lot of things now.

Then I install tcpdump and listen for 443 / 80, I see the correct IP - so nginx have to know about this.
But in my application I get only the IP from the nginx and not the original source IP! That is a huge problem.

**Comment by dinccey** [comment]
> I can't get it working too ... I tried a lot of things now.
> 
> Then I install tcpdump and listen for 443 / 80, I see the correct IP - so nginx have to know about this. But in my application I get only the IP from the nginx and not the original source IP! That is a huge problem.

Same thing here, NPM receives correct IP address as can be seen from the logs, but the target only sees proxy IP.
NPM version is 2.10.2 but the same thing occurs on 2.19.9. I migrated from an LXC running an Ubuntu image and there I would get correct IPs. Now I am using a Debian 11 VM for NPM and it does not work correctly for some reason. Any ideas?

**Comment by nfacciolo** [comment]
Use host mode in your docker compose file:

```
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```

**Comment by maixuanhan** [comment]
> this should be in the documentation !

Using host network will defeat the hostname proxy_pass (using docker service name) because other services are running in an overlay network.

**Comment by nfacciolo** [comment]
> > this should be in the documentation !
> 
> Using host network will defeat the hostname proxy_pass (using docker service name) because other services are running in an overlay network.

In production, nginx proxy manager should be the only public service, the other services are in private network linked with nginx proxy manager service

**Comment by maixuanhan** [comment]
> In production, nginx proxy manager should be the only public service, the other services are in private network linked with nginx proxy manager service

You said like you don't understand anything. The fact that you configure `host` mode in the `ports` publishing configuration does not make your nginx running in host network (or attaching to it). Setting so indeed helps nginx to actually receive packets from host port instead of some weird source, thus it can fix the surface problem.

Another problem may happen (I'm still not sure if it happens with this kind of configuration but for sure will happen if network mode of the service (not the ports) is set to host mode). For example, you run your production in a multiple-node swarm and your nginx service is deployed to some secondary node which has a different IP address (not the desired one) and it will attach to that address, your entire production is inaccessible.

Your answer is not new btw, similar answer can be found here: https://github.com/nginx-proxy/nginx-proxy/issues/133#issuecomment-754094932
My advice is to use with care.

**Comment by mellertson** [comment]
> ### **this should be in the documentation !**
> 
> Use host mode in your docker compose file:
> 
> ```
> version: '3.8'
> services:
>   app:
>     image: 'jc21/nginx-proxy-manager:latest'
>     restart: unless-stopped
>     ports:
>     ports:
>       - target: 80
>         published: 80
>         protocol: tcp
>         mode: host
>       - target: 443
>         published: 443
>         protocol: tcp
>         mode: host
>     volumes:
>       - ./data:/data
>       - ./letsencrypt:/etc/letsencrypt
> ```

This is the correct answer.  It's a matter of NAT routing, which docker implements on its ingress network.  The simple fact is that a NAT router does not forward the external client IP address by design.  So, when the NAT router, implemented by Docker, forwards packets to its running containers the client IP address does not exist in the forwarded network packet.  So, an nginx container running behind any NAT router will never be able to see the client IP address.  There are only two possible ways to fix this issue:

1. Somehow configuring NAT routing to forard the client IP address (I don't know if this is possible, maybe it is, maybe it isn't) OR
2. Connect the nginx container Docker's `host` network.

**Comment by openaspace** [comment]
my conf is: proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_headers_hash_max_size 1024;
proxy_headers_hash_bucket_size 128;
proxy_set_header X-Forwarded-Proto $scheme;
server_tokens off;
more_set_headers 'Server: MY NAME';

**Comment by x1ao4** [comment]
> You need to add this into your Custom Nginx Configuration:
> `add_header X-Frame-Options "SAMEORIGIN";`

I've configured NPM to act as a proxy for Plex and included the specified content in the Custom Nginx Configuration. Additionally, I've entered my domain name and port in Plex's Custom server access URLs. Despite this setup, Plex is still unable to obtain the actual IP address of the client. What steps should I take next?

```
proxy_hide_header Upgrade;
proxy_hide_header X-Powered-By;
add_header Content-Security-Policy "upgrade-insecure-requests";
add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Cache-Control "no-transform" always;
add_header Referrer-Policy no-referrer always;
add_header X-Robots-Tag none;
```

**Comment by chrecinos** [comment]
I have the same issue, I'm running Nginx Proxy Manager behind a router with a public IP, the router forwards the ports 80 and 443 to a Mac running Docker Desktop, where Nginx Proxy Manager is installed, I applied some of the tips here without success, my logs show the Docker network:

```
[21/Aug/2024:05:09:34 -0600] - 200 200 - GET https example.com "/" [Client 192.168.65.1] [Length 1022] [Gzip -] [Sent-to 192.168.10.5] "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0" "-"
```

```yaml
name: nginx_proxy_manager

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: NPM
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 81
        published: 81
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    environment:
      TZ: "America/New_York"
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm_user"
      DB_MYSQL_PASSWORD: "npm_pass"
      DB_MYSQL_NAME: "npm_db"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    restart: always
  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: MariaDB
    environment:
      MYSQL_ROOT_PASSWORD: 'mysqlroot'
      MYSQL_DATABASE: 'npm_db'
      MYSQL_USER: 'npm_user'
      MYSQL_PASSWORD: 'npm_pass'
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
```

Any update on how to get the clients IP would be appreciated.

**Comment by chrecinos** [comment]
Actual `/etc/nginx/nginx.conf` modified on each rebuild with `docker compose down` and `docker compose up -d`:

```
# run nginx in foreground
daemon off;
pid /run/nginx/nginx.pid;
user npm;

# Set number of worker processes automatically based on number of CPU cores.
worker_processes auto;

# Enables the use of JIT for regular expressions to speed-up their processing.
pcre_jit on;

error_log /data/logs/fallback_error.log warn;

# Includes files with directives to load dynamic modules.
include /etc/nginx/modules/*.conf;

# Custom
include /data/nginx/custom/root_top[.]conf;

events {
	include /data/nginx/custom/events[.]conf;
}

http {
	include                       /etc/nginx/mime.types;
	default_type                  application/octet-stream;
	sendfile                      on;
	server_tokens                 off;
	tcp_nopush                    on;
	tcp_nodelay                   on;
	client_body_temp_path         /tmp/nginx/body 1 2;
	keepalive_timeout             90s;
	proxy_connect_timeout         90s;
	proxy_send_timeout            90s;
	proxy_read_timeout            90s;
	ssl_prefer_server_ciphers     on;
	gzip                          on;
	proxy_ignore_client_abort     off;
	client_max_body_size          2000m;
	server_names_hash_bucket_size 1024;
	proxy_http_version            1.1;
	proxy_set_header              X-Forwarded-Scheme $scheme;
	proxy_set_header              X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header              Accept-Encoding "";
	proxy_cache                   off;
	proxy_cache_path              /var/lib/nginx/cache/public  levels=1:2 keys_zone=public-cache:30m max_size=192m;
	proxy_cache_path              /var/lib/nginx/cache/private levels=1:2 keys_zone=private-cache:5m max_size=1024m;

	# Log format and fallback log file
	include /etc/nginx/conf.d/include/log.conf;

	# Dynamically generated resolvers file
	include /etc/nginx/conf.d/include/resolvers.conf;

	# Default upstream scheme
	map $host $forward_scheme {
		default http;
	}

	# Real IP Determination

	# Local subnets:
	set_real_ip_from 0.0.0.0/0;
	# NPM generated CDN ip ranges:
	include conf.d/include/ip_ranges.conf;
	# always put the following 2 lines after ip subnets:
	real_ip_header X-Forwarded-For;
	real_ip_recursive on;

	# Custom
	include /data/nginx/custom/http_top[.]conf;

	# Files generated by NPM
	include /etc/nginx/conf.d/*.conf;
	include /data/nginx/default_host/*.conf;
	include /data/nginx/proxy_host/*.conf;
	include /data/nginx/redirection_host/*.conf;
	include /data/nginx/dead_host/*.conf;
	include /data/nginx/temp/*.conf;

	# Custom
	include /data/nginx/custom/http[.]conf;
}

stream {
	# Files generated by NPM
	include /data/nginx/stream/*.conf;

	# Custom
	include /data/nginx/custom/stream[.]conf;
}

# Custom
include /data/nginx/custom/root[.]conf;
```

Configuration 1:
```yaml
name: nginx_proxy_manager

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: NPM
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 81
        published: 81
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    environment:
      TZ: "America/New_York"
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm_user"
      DB_MYSQL_PASSWORD: "npm_pass"
      DB_MYSQL_NAME: "npm_db"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    restart: always
  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: MariaDB
    environment:
      MYSQL_ROOT_PASSWORD: 'mysqlroot'
      MYSQL_DATABASE: 'npm_db'
      MYSQL_USER: 'npm_user'
      MYSQL_PASSWORD: 'npm_pass'
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
```

Configuration 2
```yaml
name: nginx_proxy_manager

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: NPM
    network_mode: "host"
    environment:
      TZ: "America/Guatemala"
      DB_MYSQL_HOST: "localhost"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm_user"
      DB_MYSQL_PASSWORD: "npm_pass"
      DB_MYSQL_NAME: "npm_db"
      FORWARD_PROXY_SELF_SIGNED_SSL: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    restart: always

  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: MariaDB
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: 'mysqlroot'
      MYSQL_DATABASE: 'npm_db'
      MYSQL_USER: 'npm_user'
      MYSQL_PASSWORD: 'npm_pass'
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
```

```yaml
name: nginx_proxy_manager

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: NPM
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      TZ: "America/Guatemala"
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm_user"
      DB_MYSQL_PASSWORD: "npm_pass"
      DB_MYSQL_NAME: "npm_db"
      FORWARD_PROXY_SELF_SIGNED_SSL: 'true'
      REAL_IP_HEADER: 'X-Forwarded-For'
      REAL_IP_FROM: '0.0.0.0/0'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    restart: always
  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: MariaDB
    environment:
      MYSQL_ROOT_PASSWORD: 'mysqlroot'
      MYSQL_DATABASE: 'npm_db'
      MYSQL_USER: 'npm_user'
      MYSQL_PASSWORD: 'npm_pass'
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
```

In all cases, the log file it produces has the IP from the Docker network:
```
[21/Aug/2024:10:26:17 -0600] - 200 200 - GET https example.com "/" [Client 192.168.65.1] [Length 1022] [Gzip -] [Sent-to 192.168.10.5] "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0" "https://npm.cs.gt/"
```
