### ISSUE TITLE
Running NPM and PiHole at the same time

### ISSUE THREAD

**Issue by wschlotter** [jc21/nginx-proxy-manager#681]
I am wondering what the solution would be to run both NPM and PiHole on the same computer? They both say to use port 80 and 443.

**Comment by aronwk-aaron** [comment]
If you are using docker, you can just change the mapped ports on one (or in my case, both) of the containers

**Comment by wschlotter** [comment]
I understand that, but both say that is ill advised. I did have NPM running on a different port bu them me Lets Encrypt did renew the certificates.

**Comment by jlnwlf** [comment]
I came up with changing the port used by `lighttpd` for pi-hole (not in a container) from `80` to `8017` and made a proxy host entry in NPM to point to the lighttpd server on port `8017`.

Depending on your requirements/network/use case, that might not be enough though...

**Comment by rastacalavera** [comment]
I am in this situation. I want to run pihole rather than adguard home. I run all my docker containers on a pi4 and want to include pihole in this setup. I can get pihole running using this compose file
```pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "6876:53/tcp"
      - "6877:53/udp"
      - "6879:67/udp"
      - "6880:80/tcp"
      - "6881:443/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: '1234'
      ServerIP: '192.168.0.140'
      PROXY_LOCATION: pihole'
      VIRTUAL_HOST: 'pihole.mydomain.net'
      VIRTUAL_PORT: '80'
      DNS1: '127.0.0.1'
      DNS2: '1.1.1.1'
   # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'    # Recommended but not required (DHCP needs NET_ADMIN)
      https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
   cap_add:
     - NET_ADMIN
    restart: unless-stopped```

**Comment by crazybadger** [comment]
I'm not convinced running them on the same machine is sensible, given one is trying to route external requests and the other is trying to block some internal ones.  They work well on the same network given then own IP stack though!

**Comment by rastacalavera** [comment]
> I'm not convinced running them on the same machine is sensible, given one is trying to route external requests and the other is trying to block some internal ones. They work well on the same network given then own IP stack though!

Yeah I have used them separately before, it is just a nice attraction to consolidate onto a single machine. I dedicated my other pi to home assistant, and they have adguard as an extension but i prefer pihole.

**Comment by crazybadger** [comment]
You could run NPM as a Home Assistant Add On and then use your other Pi for Pi-Hole?  I have NPM running on a Hass.io Pi and  Pi-hole running on a FreeNAS VM.

**Comment by jc21** [comment]
Wait hang on, I don't use pi-hole but from what I've read in their documentation it's just a DNS sinkhole with an optional VPN. As a DNS sinkhole, NPM does not conflict as it doesn't run a DNS server. There should not be an issue running them on the same machine. Pi-hole's web interface can run on any port, npm can proxy to it. Pi-hole's DNS server can run on the standard port 53 and NPM won't care.

Unless I'm missing something here?

In addition to running these together on the same machine: if you utilize docker networks and don't map pi-hole's ports to the docker host, you won't need to change ports and instead add a stream to forward 53 to pi-hole as well:

```bash
docker network create skynet
```

```yml
version: "3"
services:
  npm:
    image: jc21/nginx-proxy-manager:2
    container_name: npm
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
      - 53:53
    volumes:
      ...

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      ...
    volumes:
      ...
    restart: unless-stopped

networks:
  default:
    external:
      name: skynet
```

Then add a proxy host for pi-hole with hostname `pihole` on either `80` or `443`, then add a stream to `pihole` on port `53`. These services will be contained in the same virtual network named `skynet` and the only service being exposed directly is NPM. This is how I run all my services but once again I haven't tested this with pi-hole myself.

**Comment by rastacalavera** [comment]
Really appreciate the reply! 
I decided to try everything on a fresh install of Ubuntu 20.04 on a raspberryPi 4.
There are some new errors that are cropping up. 
Here are the errors I am seeing:
```
Creating pihole ... 
Creating ubuntu_db_1 ... 

ERROR: for pihole  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for ubuntu_db_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for pihole  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for db  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
ubuntu@ubuntu:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
ubuntu@ubuntu:~$ docker-compose up -d
Starting ubuntu_db_1 ... done
Starting pihole      ... done
Creating npm         ... 
Creating npm         ... error

ERROR: for npm  Cannot start service app: driver failed programming external connectivity on endpoint npm (be909651750d0150cb67602ba2cf0a63a99b3226b523988da8d0cbd579903e58): Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address already in use

ERROR: for app  Cannot start service app: driver failed programming external connectivity on endpoint npm (be909651750d0150cb67602ba2cf0a63a99b3226b523988da8d0cbd579903e58): Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```
When I run sudo lsof -i :53 to see what is on port 53 here is the output:
```
sudo lsof -i :53
COMMAND     PID            USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
systemd-r 19641 systemd-resolve   12u  IPv4  85100      0t0  UDP localhost:domain 
systemd-r 19641 systemd-resolve   13u  IPv4  85101      0t0  TCP localhost:domain (LISTEN)
```
This is my SECOND time attempting this, the first time I followed the directions [here](https://www.linuxuprising.com/2020/07/ubuntu-how-to-free-up-port-53-used-by.html) on how to get systemd-resolve to get off that port but then all of my apt commands were broken and I couldn't fix them and had to do a clean install again.

Here is the compose file
```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
      #added from github open issues
      - 53:53/tcp
      - 53:53/udp
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: jc21/mariadb-aria:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
#      - opt/appdata/mariadb/data/mysql:/var/lib/mysql
      - ./data/mysql:/var/lib/mysql
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: '1234'
    volumes:
      - '/opt/appdata/pihole/etc-pihole/:/etc/pihole/'
      - '/opt/appdata/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped

networks:
  default:
    external:
      name: skynet
```

**Comment by rastacalavera** [comment]
Ok i think I am getting closer. I made some changes to the Docker-Compose file and that will be included last.
Now I have access to the NPM and PiHole Web GUIs but I am not confident that I am setting up the host or stream in NPM. Here are some [images](https://imgur.com/a/8HHnqdc) to show the setup.
I have never done a stream before. . . 

Here is my new compose file. I had to change the DB (issue on this for RPi) and added in some environmental variables for PiHole. I did see way down in the documentation of PiHole that they say how to solve the port 53 issue on Ubuntu so shame on me for not reading everything :P I don't know if I needed the ports in PiHole but I couldn't get the the GUI without them.
```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
      #added from github open issues
      - 53:53/tcp
      - 53:53/udp
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: yobasystems/alpine-mariadb:armhf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
#      - opt/appdata/mariadb/data/mysql:/var/lib/mysql
      - ./data/mysql:/var/lib/mysql
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "6876:53/tcp"
      - "6877:53/udp"
      - "6879:67/udp"
      - "6880:80/tcp"
      - "6881:443/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: '1234'
      ServerIP: '192.168.0.140'
#      PROXY_LOCATION: pihole'
#      VIRTUAL_HOST: 'pihole.mydomain.net'
#      VIRTUAL_PORT: '80'
#      DNS1: '127.0.0.1'
#      DNS2: '1.1.1.1'
    volumes:
      - '/opt/appdata/pihole/etc-pihole/:/etc/pihole/'
      - '/opt/appdata/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped

networks:
  default:
    external:
      name: skynet
```
