### ISSUE TITLE
2.7.0 not starting

### ISSUE THREAD

**Issue by rlogiacco** [jc21/nginx-proxy-manager#728]
**Checklist**

- [x] Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
- [x] Are you sure you're not using someone else's docker image?
- [x] If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?

**Describe the bug**
Container doesn't start reporting: 
```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
❯ Enabling IPV6 in hosts: /etc/nginx/conf.d,
  ❯ /etc/nginx/conf.d/default.conf,
  ❯ /etc/nginx/conf.d/include/assets.conf,
  ❯ /etc/nginx/conf.d/include/block-exploits.conf,
  ❯ /etc/nginx/conf.d/include/force-ssl.conf,
  ❯ /etc/nginx/conf.d/include/ip_ranges.conf,
  ❯ /etc/nginx/conf.d/include/letsencrypt-acme-challenge.conf,
  ❯ /etc/nginx/conf.d/include/proxy.conf,
  ❯ /etc/nginx/conf.d/include/ssl-ciphers.conf,
  ❯ /etc/nginx/conf.d/include/resolvers.conf,
  ❯ /etc/nginx/conf.d/production.conf,
❯ Enabling IPV6 in hosts: /data/nginx,
  ❯ /data/nginx/proxy_host/2.conf,
  ❯ /data/nginx/proxy_host/1.conf,
finish: applet not found,
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
```
- Unable to access on the login page, but I'm starting image tagged `2.7.0`

**To Reproduce**
1. Change a stack happily running `2.6.2` to `2.7.0`

**Expected behavior**
Container starting

**Screenshots**
Not applicable

**Operating System**
RedHat EL 7.9

**Additional context**
Deploying as a stack containing both this container image and mariadb, using NFS mounted volumes ina 3 nodes swarm

**Comment by rlogiacco** [comment]
Switching back to 2.6.2 (nothing else changes other than the image tag) fixes the issue

**Comment by jc21** [comment]
Hmm yes I can definitely reproduce this problem in one of my deployments. How embarrassing...

**Comment by themreza** [comment]
Just out of curiosity, are there any build checks (e.g. unit tests, e2e tests) in place before releasing a version?

**Comment by rlogiacco** [comment]
> Hmm yes I can definitely reproduce this problem in one of my deployments. How embarrassing...

Sorry for doing this, but I'm blocked on 2.6.2 by #594 : will 2.7.0 fix that or can you give me instructions on how to get around the issue? I'm currently looking into the source files to verify if I can get any progress on that as that's blocking for me

**Comment by jc21** [comment]
v2.7.1 is released now to fix non-starts.

As for the custom cert issue, I'll bump it to the top of my todo list

**Comment by Riku32** [comment]
This still happens to me. Docker stack file below.
```yml
version: "3.4"
services:
  app:
    image: 'jc21/nginx-proxy-manager:v2.7.1'
    restart: always
    ports:
      # Public HTTP Port:
      - 8081:8081
      # Public HTTPS Port:
      - 8443:8443
      # Admin Web Port:
      - 8080:8080
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: 'true'
    volumes:
      - nginx_proxy_data:/data
      - nginx_proxy_letsencrypt:/etc/letsencrypt

volumes:
  nginx_proxy_data:
    name: nginx_proxy_data
  nginx_proxy_letsencrypt:
    name: nginx_proxy_letsencrypt

networks:
  default:
    external:
      name: main
```
