### ISSUE TITLE
Nginx can't generate certs for certain containers

### ISSUE THREAD

**Issue by lborruto** [jc21/nginx-proxy-manager#778]
**Describe the bug**
Just finished moving from [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy) and the [letsencrypt-companion](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion) to try nginx-proxy-manager, and I have the [same issue](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/731) as previously with nginx-proxy.

With some of my containers (ex: [Jellyfin](https://github.com/jellyfin/jellyfin)) it works great, but with other (ex: [Overseerr](https://github.com/sct/overseerr), [MovieMatch](https://github.com/LukeChannings/moviematch)), Nginx can't generate a certificate:

```
[12/17/2020] [9:10:42 AM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-2" --agree-tos --email "mail@domain.com" --preferred-challenges "dns,http" --domains "sub.domain.com" 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for sub.domain.com
Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
Waiting for verification...
Challenge failed for domain sub.domain.com
http-01 challenge for sub.domain.com
Cleaning up challenges
Some challenges have failed.
```

I'm using the version `v2.7.1`, and I switched my containers to be in the same network as Nginx: `nginx_default`

My `docker-compose.yml` : 

```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-manager
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:10.4'
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./nginx/data/mysql:/var/lib/mysql
```

**Operating System**
I'm cloud hosting my server:
```
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

Also just figured out another issue, I tried with my phone in 4G and got this error trying to access the same page (Jellyfin container works also fine with 4G, but not Overseerr or MovieMatch) :

`Forbidden, you don't have the permission to access this ressource.`

Any help would be appreciated!
