### ISSUE TITLE
Bad gateway and database error

### ISSUE THREAD

**Issue by joergklein** [jc21/nginx-proxy-manager#797]
CentOS 7 on a Virual Server. httpd is down. 
I used this docker-compose.yml

```
[version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:10.4.12'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
](url)
```

When I start docker-compose.yml without -d to see all errors. I get this error

```
app_1  | ❯ Enabling IPV6 in hosts: /data/nginx
app_1  | [1/2/2021] [3:50:42 PM] [Global   ] › ℹ  info      Generating MySQL db configuration from environment variables
app_1  | [1/2/2021] [3:50:42 PM] [Global   ] › ℹ  info      Wrote db configuration to config file: ./config/production.json
db_1   | 2021-01-02 15:50:43 3 [Warning] Access denied for user 'npm'@'172.18.0.3' (using password: YES)
app_1  | [1/2/2021] [3:50:43 PM] [Global   ] › ✖  error     ER_ACCESS_DENIED_ERROR: Access denied for user 'npm'@'172.18.0.3' (using password: YES)
db_1   | 2021-01-02 15:50:44 4 [Warning] Access denied for user 'npm'@'172.18.0.3' (using password: YES)
```

When I use docker-compose -d and start the NGINX roxy in the subdomain proxy.example.com.  I get the error message `Bad gateway`.
