### ISSUE TITLE
How do I automatically redirect http to https?

### ISSUE THREAD

**Issue by Pistrie** [jc21/nginx-proxy-manager#886]
In my example, I have a Bitwarden vault located at example.duckdns.org. If I approach this by https://www.example.duckdns.org then everything is fine. However, I can also approach it by manually typing http://www.example.duckdns.org, which will bring me to the unsecured version of the website, which is not what I want. How do I automatically redirect the http request to https? I looked at the advanced tab and saw a variable called $forward_scheme, but I'm not quite proficient in Nginx yet.

**Comment by lieven121** [comment]
Have you tried forcing ssl ?
![image](https://user-images.githubusercontent.com/7773244/107613415-90570800-6c48-11eb-8312-a2b2370342bd.png)

**Comment by Pistrie** [comment]
I swear I clicked that button when generating the certificate, but double-checking shows it was disabled. Thanks a bunch, it did the trick!

**Comment by huangwb8** [comment]
@Pistrie How do you interact NPM with Bitwarden? The tutorial is rare in the internet.

Would you please demonstrate your installion strategy? Thanks!

**Comment by Pistrie** [comment]
I simply make http ip:port of the vaultwarden server available on a specific subdomain, just like any other service. I'm not sure where your confusion comes from.

**Comment by huangwb8** [comment]
@Pistrie Thanks, I had succeed! 

In the begining, I built bitwarden and npm as a service in a special network, and I found it difficult to set up nginx setting. Afterwards, I just use my default npm to do proxy things, and it works perfect! 

Here is the demo that show how I set bitwarden via NPM:

```yaml
version: "2"

networks:
  net:
    name: bitwarden

services:
  app:
    image: vaultwarden/server:latest
    environment:
      - SERVER_ADMIN_EMAIL=example@gmail.com
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=true
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=<unique token>
    volumes:
      - ./app:/data/
    ports:
      - 6539:80
    restart: unless-stopped
    networks:
      - net
```
just :

```bash
docker-compose up -d
```
Create a `Proxy host`, set DESTINATION as `http://server.ip:6539`. Get a `bitwarden.exampledomain.com` for https and ssl certificates.

Visit: `http://server.ip:6539/admin` or `https://bitwarden.exampledomain.com`  , use `ADMIN_TOKEN` to enter the dashboard. 

In `General settings`,  set URL as `http://server.ip:6539/admin`.

Set `SMTP Email Settings`.

In the `User` section, send inviting email to a user.

Done!
