### ISSUE TITLE
Only one domain works at any given time.

### ISSUE THREAD

**Issue by randy-girard** [jc21/nginx-proxy-manager#889]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?

Yes

```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
```

- Are you sure you're not using someone else's docker image?

Yes

- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?

N/A (I think)

**Describe the bug**

I have added three proxies to my application that go to three different back end servers. It seems like only the last one I add/update actually works. The other two will just timeout. I also don't see any traffic coming to the domains that are no active. All three of the domains are reporting the correct IP address via `ping`.

- What version of Nginx Proxy Manager is reported on the login page?

v2.8.0 

**Operating System**

- I am using a VM via proxmox to run NginxProxyManager on. The other apps are on seperate vms that are accessible via the IP/hostname locally. These are the ip addresses and ports used for the proxies.
