### ISSUE TITLE
Set client_max_body_size and other Nginx configrations

### ISSUE THREAD

**Issue by relink2013** [jc21/nginx-proxy-manager#93]
I need to add a `client_max_body_size  10000m;` to one of my proxy hosts, but there seems to be no obvious way to do it. I tried adding it directly to the .conf file, but it did not work.

**Comment by jc21** [comment]
At the moment you can't. But I'll convert this to a future feature.

**Comment by xhaloz** [comment]
> 
> 
> At the moment you can't. But I'll convert this to a future feature.

So what is the work around for this? My nextcloud photo uploads are so slow.

**Comment by UniverseXXX** [comment]
I also have a lot of customisations in nginx.conf file (e.g. add_header, ssl_, gzip_, proxy_, auth_basic_ etc.). Not being able set it manually in the Manager is stopping me from moving to here. Otherwise, idea/app is brilliant. Thanks.

**Comment by niklasdahlheimer** [comment]
Hey
Great app so far!
I also need to edit the nginx.conf and add 
`client_max_body_size 0`
to prevent a timeout while uploading a lot of data at once
Seems like the nginx.conf is not part of the mountable /conf folder. Is there any way to edit the nginx.conf via SSH opening a bash in the container?

**Comment by jc21** [comment]
For the time being here's a hack:

Connect to your already running NPM container with

```bash
docker exec -ti name_of_container bash
```
and then
```bash
cp /etc/nginx/nginx.conf /data/nginx/`
```
So what you just did was enter the running container filesystem and copy the built-in `nginx.conf` file to your mounted data folder.

Now you have to bring down your docker containers and forcibly mount the `nginx.conf` file over the top of the built in one. You'll have to edit your `docker-compose.yml` file or however you run your container to mount it:

```yml
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./data/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
```
Make changes to your version of the config and restart the container to take effect.
