### ISSUE TITLE
Unable to start service db - first time setup

### ISSUE THREAD

**Issue by charles-997** [jc21/nginx-proxy-manager#941]
Hi all,

I'm having trouble getting this running via docker-compose on my Ubuntu server.
Here is the text of my docker-compose file.  I have followed the [Full Setup Instructions here](https://nginxproxymanager.com/setup/#full-setup-instructions)
## Docker-compose file
```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "**********"
      DB_MYSQL_PASSWORD: "**********"
      DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '**********'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: '**********'
      MYSQL_PASSWORD: '**********'
    volumes:
      - ./data/mysql:/var/lib/mysql
```

## Error Messages
When I try to bring the stack up, these are the errors I am receiving.

```
charles@ubuntuVM:/nfs/docker/nginxreverseproxy$ docker-compose up -d
Creating network "nginxreverseproxy_default" with the default driver
Creating nginxreverseproxy_db_1 ... error

ERROR: for nginxreverseproxy_db_1  Cannot start service db: error while creating mount source path '/nfs/docker/nginxreverseproxy/data/mysql': chown /nfs/docker/nginxreverseproxy/data/mysql: operation not permitted

ERROR: for db  Cannot start service db: error while creating mount source path '/nfs/docker/nginxreverseproxy/data/mysql': chown /nfs/docker/nginxreverseproxy/data/mysql: operation not permitted
ERROR: Encountered errors while bringing up the project.
```
## Hypothesis
I am suspecting the problem is related to the permissions on the directory `/nfs/docker/nginxreverseproxy`.  This directory is a NFS share from my TrueNAS server mounted on the Ubuntu server (docker host).

### Permissions settings
The Ubuntu server (client/docker host) has user `charles` which has UID and GID of 1000.
The TrueNAS server has a dataset called `nginxreverseproxy` which has permissions set as such:

user: UID 1000
group: GID 1000
owner@, group@, everyone@ all have permissions set to Full Control.

The TrueNAS NFS share settings are as follows:
All dirs - True
Quiet - False
Enabled - True

Read-only - False

maproot User - (blank)
maproot Group - (blank)
mapall user - TrueNAS user with UID 1000
mapall group - TrueNAS group with GID 1000

Authorized networks - (blank, thus allow all)
Authorized hosts - (blank, thus allow all)

## Conclusion

I have the rest of my containers setup with the exact same settings on their own datasets using TrueNAS for storage so I'm not convinced the error actually has to do with the stoarge infrastructure, however the "chown operation not permitted" error messages make me think its storage permissions related?

Any help is much appreciated, I have been pulling my hair out trying to figure out why i am continuously getting the same issue with Nginx Reverse Proxy Manager.
